<a href="https://colab.research.google.com/github/GaneshShindee/Machine-Learning/blob/main/Essentials_of_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Introduction
NumPy is a powerful numerical computing library in Python. It provides support for arrays, matrices, and many mathematical functions. This notebook covers the essentials of NumPy, starting from the basics and gradually extending to more complex topics.

###Table of Contents
1. Introduction to NumPy
2. NumPy Arrays
  * Creating Arrays
  * Array Indexing and Slicing
  * Array Properties
3. Array Operations
  * Arithmetic Operations
  * Universal Functions (ufuncs)
  * Broadcasting
4. Mathematical Functions
  * Aggregation Functions
  * Trigonometric Functions
  * Exponential and Logarithmic Functions
5. Random Numbers
  * Random Number Generation
  * Statistical Functions

#1. Introduction to NumPy

NumPy (Numerical Python) is the foundational package for scientific computing in Python. It is highly efficient, providing support for large multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays.



In [ ]:
import numpy as np
print("NumPy version:", np.__version__)

NumPy version: 1.25.2


#2. NumPy Arrays
##Creating Arrays
###2.1.1 From Python Lists

In [ ]:
import numpy as np

# Creating a 1D array from a list
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D array:", arr_1d)

# Creating a 2D array from a list of lists
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array:\n", arr_2d)

1D array: [1 2 3 4 5]
2D array:
 [[1 2 3]
 [4 5 6]]


###2.1.2 Using NumPy Functions


In [ ]:
# Creating an array of zeros
arr_zeros = np.zeros((3, 3))
print("Array of zeros:\n", arr_zeros)

# Creating an array of ones
arr_ones = np.ones((2, 4))
print("Array of ones:\n", arr_ones)

# Creating an array with a range of values
arr_range = np.arange(0, 10, 2)
print("Array with a range of values:", arr_range)

# Creating an array of evenly spaced values
arr_linspace = np.linspace(0, 1, 5)
print("Array of evenly spaced values:", arr_linspace)

Array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array of ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Array with a range of values: [0 2 4 6 8]
Array of evenly spaced values: [0.   0.25 0.5  0.75 1.  ]


###2.1.3 From Functions


In [ ]:
# Creating an array from a function
arr_from_function = np.fromfunction(lambda i, j: i + j, (3, 3), dtype=int)
print("Array from function:\n", arr_from_function)

Array from function:
 [[0 1 2]
 [1 2 3]
 [2 3 4]]


##Array Indexing and Slicing
###2.2.1 Indexing


In [ ]:
# Accessing elements in a 1D array
print("First element:", arr_1d[0])
print("Last element:", arr_1d[-1])

# Accessing elements in a 2D array
print("Element at (0,1):", arr_2d[0, 1])
print("Element at (1,2):", arr_2d[1, 2])

First element: 1
Last element: 5
Element at (0,1): 2
Element at (1,2): 6


###2.2.2 Slicing


In [ ]:
# Slicing a 1D array
print("Sliced 1D array:", arr_1d[1:4])

# Slicing a 2D array
print("Sliced 2D array:\n", arr_2d[:, 1:3])

Sliced 1D array: [20 30 40]
Sliced 2D array:
 [[20 30]
 [50 60]
 [80 90]]


In [ ]:
import numpy as np

# Example 1D array
arr_1d = np.array([10, 20, 30, 40, 50])
print("Sliced 1D array:", arr_1d[1:4])

# Example 2D array
arr_2d = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])
print("Sliced 2D array:\n", arr_2d[:, 1:3])


Sliced 1D array: [20 30 40]
Sliced 2D array:
 [[20 30]
 [50 60]
 [80 90]]


##Array Properties


In [ ]:
# Shape of the array
print("Shape of 1D array:", arr_1d.shape)
print("Shape of 2D array:", arr_2d.shape)

# Number of dimensions
print("Number of dimensions of 1D array:", arr_1d.ndim)
print("Number of dimensions of 2D array:", arr_2d.ndim)

# Size of the array (number of elements)
print("Size of 1D array:", arr_1d.size)
print("Size of 2D array:", arr_2d.size)

# Data type of the elements
print("Data type of 1D array:", arr_1d.dtype)
print("Data type of 2D array:", arr_2d.dtype)


Shape of 1D array: (5,)
Shape of 2D array: (3, 3)
Number of dimensions of 1D array: 1
Number of dimensions of 2D array: 2
Size of 1D array: 5
Size of 2D array: 9
Data type of 1D array: int32
Data type of 2D array: int32


#3. Array Operations
##Arithmetic Operations


In [ ]:
arr_a = np.array([1, 2, 3])
arr_b = np.array([4, 5, 6])

# Addition
print("Addition:", arr_a + arr_b)

# Subtraction
print("Subtraction:", arr_a - arr_b)

# Multiplication
print("Multiplication:", arr_a * arr_b)

# Division
print("Division:", arr_a / arr_b)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


##Universal Functions (ufuncs)


In [ ]:
# Square root
print("Square root:", np.sqrt(arr_a))

# Exponential
print("Exponential:", np.exp(arr_a))

# Sine
print("Sine:", np.sin(arr_a))

Square root: [1.         1.41421356 1.73205081]
Exponential: [ 2.71828183  7.3890561  20.08553692]
Sine: [0.84147098 0.90929743 0.14112001]


##Broadcasting


In [ ]:
arr_c = np.array([[1, 2, 3], [4, 5, 6]])

# Broadcasting with a scalar
print("Broadcasting with scalar:\n", arr_c + 10)

# Broadcasting with a 1D array
arr_d = np.array([1, 2, 3])
print("Broadcasting with 1D array:\n", arr_c + arr_d)


Broadcasting with scalar:
 [[11 12 13]
 [14 15 16]]
Broadcasting with 1D array:
 [[2 4 6]
 [5 7 9]]


#4. Mathematical Functions
##Aggregation Functions


In [ ]:
# Sum
print("Sum:", np.sum(arr_c))

# Mean
print("Mean:", np.mean(arr_c))

# Standard Deviation
print("Standard Deviation:", np.std(arr_c))

Sum: 21
Mean: 3.5
Standard Deviation: 1.707825127659933


##Trigonometric Functions


In [ ]:
# Sine
print("Sine of pi/2:", np.sin(np.pi/2))

# Cosine
print("Cosine of pi:", np.cos(np.pi))

Sine of pi/2: 1.0
Cosine of pi: -1.0


##Exponential and Logarithmic Functions


In [ ]:
# Exponential
print("Exponential of 1:", np.exp(1))

# Natural logarithm
print("Natural log of e:", np.log(np.e))

# Base-10 logarithm
print("Log base 10 of 100:", np.log10(100))

Exponential of 1: 2.718281828459045
Natural log of e: 1.0
Log base 10 of 100: 2.0


#5. Random Numbers
##Random Number Generation



In [ ]:
# Random integers
rand_ints = np.random.randint(1, 10, size=(3, 3))
print("Random integers:\n", rand_ints)

# Random floats
rand_floats = np.random.rand(3, 3)
print("Random floats:\n", rand_floats)

# Random normal distribution
rand_normal = np.random.randn(3, 3)
print("Random normal distribution:\n", rand_normal)

Random integers:
 [[4 2 6]
 [7 4 2]
 [5 4 2]]
Random floats:
 [[0.68665301 0.12294257 0.69137213]
 [0.97528824 0.4463305  0.43416095]
 [0.13571107 0.04538699 0.99464257]]
Random normal distribution:
 [[-0.78604876  0.91961384 -1.16038452]
 [-0.39311416  0.71023339  0.16629424]
 [ 0.90152279 -0.20351894  0.44100664]]


##Statistical Functions


In [ ]:
# Mean of random normal distribution
print("Mean of random normal distribution:", np.mean(rand_normal))

# Standard deviation of random normal distribution
print("Standard deviation of random normal distribution:", np.std(rand_normal))

Mean of random normal distribution: 0.06617827860357489
Standard deviation of random normal distribution: 0.7075711640678294
